import Audio1 from '../assests/audio/lazy-day.mp3';
import Audio2 from '../assests/audio/creative-technology.mp3';
import Audio3 from '../assests/audio/lost-in-dreams.mp3';
import Audio4 from '../assests/audio/nightfall.mp3';
import Audio5 from '../assests/audio/showreel.mp3';
import Audio6 from '../assests/audio/soulsweeper.mp3';
import Audio7 from '../assests/audio/spinning-head.mp3';
import Audio8 from '../assests/audio/stylish-deep.mp3';
import Audio9 from '../assests/audio/tell-me-the-truth.mp3';
import Audio10 from '../assests/audio/vlog.mp3';

export const mockTracks = [
  {
    id: 1,
    title: 'Lazy Day',
    artist: 'Spotify AYDT',
    coverUrl: 'https://picsum.photos/200?random=1',
    audio: Audio1,
    duration: '3:45',
    album: 'Chill Vibes',
    releaseYear: 2024,
    genre: 'Lo-Fi',
    isLiked: true,
    plays: 1250,
    addedDate: '2024-01-15',
    lyrics: true,
    explicit: false,
    mood: 'Relaxing',
  },
  {
    id: 2,
    title: 'Creative Technology',
    artist: 'Tech Beats',
    coverUrl: 'https://picsum.photos/200?random=2',
    audio: Audio2,
    duration: '4:20',
    album: 'Digital Age',
    releaseYear: 2024,
    genre: 'Electronic',
    isLiked: false,
    plays: 850,
    addedDate: '2024-01-16',
    lyrics: false,
    explicit: false,
    mood: 'Energetic',
  },
  {
    id: 3,
    title: 'Lost in Dreams',
    artist: 'Luna & The Stars',
    coverUrl: 'https://picsum.photos/200?random=3',
    audio: Audio3,
    duration: '3:15',
    album: 'Midnight Tales',
    releaseYear: 2023,
    genre: 'Dream Pop',
    isLiked: true,
    plays: 2100,
    addedDate: '2023-12-20',
    lyrics: true,
    explicit: false,
    mood: 'Dreamy',
  },
  {
    id: 4,
    title: 'Nightfall',
    artist: 'Synthwave Riders',
    coverUrl: 'https://picsum.photos/200?random=4',
    audio: Audio4,
    duration: '5:30',
    album: 'Retro Future',
    releaseYear: 2024,
    genre: 'Synthwave',
    isLiked: true,
    plays: 1800,
    addedDate: '2024-01-10',
    lyrics: false,
    explicit: false,
    mood: 'Atmospheric',
  },
  {
    id: 5,
    title: 'Showreel',
    artist: 'Visual Beats',
    coverUrl: 'https://picsum.photos/200?random=5',
    audio: Audio5,
    duration: '4:10',
    album: 'Portfolio Mix',
    releaseYear: 2023,
    genre: 'Ambient',
    isLiked: false,
    plays: 650,
    addedDate: '2023-11-30',
    lyrics: false,
    explicit: false,
    mood: 'Focused',
  },
  {
    id: 6,
    title: 'Soulsweeper',
    artist: 'Deep Vibes',
    coverUrl: 'https://picsum.photos/200?random=6',
    audio: Audio6,
    duration: '3:55',
    album: 'Soul Sessions',
    releaseYear: 2024,
    genre: 'Deep House',
    isLiked: true,
    plays: 3200,
    addedDate: '2024-01-05',
    lyrics: true,
    explicit: true,
    mood: 'Groovy',
  },
  {
    id: 7,
    title: 'Spinning Head',
    artist: 'The Groove Masters',
    coverUrl: 'https://picsum.photos/200?random=7',
    audio: Audio7,
    duration: '6:15',
    album: 'Late Night Sessions',
    releaseYear: 2023,
    genre: 'Jazz Fusion',
    isLiked: false,
    plays: 920,
    addedDate: '2023-12-15',
    lyrics: false,
    explicit: false,
    mood: 'Jazzy',
  },
  {
    id: 8,
    title: 'Stylish Deep',
    artist: 'Urban Flow',
    coverUrl: 'https://picsum.photos/200?random=8',
    audio: Audio8,
    duration: '4:45',
    album: 'City Lights',
    releaseYear: 2024,
    genre: 'Deep House',
    isLiked: true,
    plays: 1500,
    addedDate: '2024-01-08',
    lyrics: true,
    explicit: false,
    mood: 'Smooth',
  },
  {
    id: 9,
    title: 'Tell Me The Truth',
    artist: 'Soul Speakers',
    coverUrl: 'https://picsum.photos/200?random=9',
    audio: Audio9,
    duration: '5:20',
    album: 'Raw Emotions',
    releaseYear: 2023,
    genre: 'Soul',
    isLiked: true,
    plays: 4100,
    addedDate: '2023-12-01',
    lyrics: true,
    explicit: true,
    mood: 'Emotional',
  },
  {
    id: 10,
    title: 'Vlog Life',
    artist: 'Content Creators',
    coverUrl: 'https://picsum.photos/200?random=10',
    audio: Audio10,
    duration: '3:30',
    album: 'Digital Stories',
    releaseYear: 2024,
    genre: 'Pop',
    isLiked: false,
    plays: 750,
    addedDate: '2024-01-12',
    lyrics: false,
    explicit: false,
    mood: 'Upbeat',
  },
];
